export const ErrorCode = {
  // Generic fallbacks (assigned by the filter to legacy/unconverted exceptions)
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_MISSING_HEADER: 'AUTH_MISSING_HEADER',
  AUTH_MISSING_CODE: 'AUTH_MISSING_CODE',
  AUTH_PROVIDER_DISABLED: 'AUTH_PROVIDER_DISABLED',
  AUTH_OAUTH_EMAIL_MISSING: 'AUTH_OAUTH_EMAIL_MISSING',
  AUTH_OAUTH_REJECTED: 'AUTH_OAUTH_REJECTED',
  AUTH_OAUTH_EXCHANGE_FAILED: 'AUTH_OAUTH_EXCHANGE_FAILED',
  AUTH_SIGNUP_FAILED: 'AUTH_SIGNUP_FAILED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
  AUTH_RESET_FAILED: 'AUTH_RESET_FAILED',

  // School-domain provisioning: verify-before-reveal + credential recovery
  CREDENTIALS_ENCRYPTION_NOT_CONFIGURED:
    'CREDENTIALS_ENCRYPTION_NOT_CONFIGURED',
  VERIFY_TOKEN_INVALID: 'VERIFY_TOKEN_INVALID',
  VERIFY_TOKEN_EXPIRED: 'VERIFY_TOKEN_EXPIRED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  GUARDIAN_REQUIRED: 'GUARDIAN_REQUIRED',
  GUARDIAN_VERIFY_REQUIRED: 'GUARDIAN_VERIFY_REQUIRED',
  ALREADY_ONBOARDED: 'ALREADY_ONBOARDED',
  ONBOARDING_INPUT_REQUIRED: 'ONBOARDING_INPUT_REQUIRED',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_ALREADY_MEMBER: 'GROUP_ALREADY_MEMBER',
  GROUP_REQUIRES_ENTERPRISE: 'GROUP_REQUIRES_ENTERPRISE',

  // Struggle signals (post-meeting follow-up)
  STRUGGLE_SIGNAL_NOT_FOUND: 'STRUGGLE_SIGNAL_NOT_FOUND',
  STRUGGLE_SIGNAL_NOT_ACTIONABLE: 'STRUGGLE_SIGNAL_NOT_ACTIONABLE',
  STRUGGLE_SIGNAL_FORBIDDEN: 'STRUGGLE_SIGNAL_FORBIDDEN',
  STRUGGLE_GENERATION_FAILED: 'STRUGGLE_GENERATION_FAILED',

  // Subscription / billing / organizations
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  TIER_REQUIRED: 'TIER_REQUIRED',
  PLAN_NOT_AVAILABLE: 'PLAN_NOT_AVAILABLE',
  BILLING_NO_SUBSCRIPTION: 'BILLING_NO_SUBSCRIPTION',
  BILLING_NO_ITEMS: 'BILLING_NO_ITEMS',
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_FORBIDDEN: 'ORG_FORBIDDEN',
  INVITE_EMAIL_INVALID: 'INVITE_EMAIL_INVALID',
  INVITE_EMAIL_TAKEN: 'INVITE_EMAIL_TAKEN',
  INVITE_SEATS_FULL: 'INVITE_SEATS_FULL',
  JOIN_CODE_INVALID: 'JOIN_CODE_INVALID',
  REQUEST_ALREADY_EXISTS: 'REQUEST_ALREADY_EXISTS',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_RESOLVED: 'REQUEST_ALREADY_RESOLVED',
  SCHOOL_CODE_INVALID: 'SCHOOL_CODE_INVALID',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  ALREADY_APPLIED: 'ALREADY_APPLIED',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_NOT_PENDING: 'JOIN_REQUEST_NOT_PENDING',
  WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_MISSING_PAYLOAD: 'WEBHOOK_MISSING_PAYLOAD',
  WEBHOOK_UNCONFIGURED: 'WEBHOOK_UNCONFIGURED',

  // Grade levels / sections / courses / offerings
  GRADE_LEVEL_NOT_FOUND: 'GRADE_LEVEL_NOT_FOUND',
  GRADE_LEVEL_CONFLICT: 'GRADE_LEVEL_CONFLICT',
  SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
  SECTION_CONFLICT: 'SECTION_CONFLICT',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_CONFLICT: 'COURSE_CONFLICT',
  OFFERING_NOT_FOUND: 'OFFERING_NOT_FOUND',
  OFFERING_CONFLICT: 'OFFERING_CONFLICT',
  TIMETABLE_SLOT_NOT_FOUND: 'TIMETABLE_SLOT_NOT_FOUND',
  TIMETABLE_TEACHER_CONFLICT: 'TIMETABLE_TEACHER_CONFLICT',
  TIMETABLE_SECTION_CONFLICT: 'TIMETABLE_SECTION_CONFLICT',
  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',

  // Quizzes
  QUIZ_NOT_FOUND: 'QUIZ_NOT_FOUND',
  QUIZ_DRAFT_ONLY: 'QUIZ_DRAFT_ONLY',
  QUIZ_NOT_PUBLISHED: 'QUIZ_NOT_PUBLISHED',
  QUIZ_FORBIDDEN: 'QUIZ_FORBIDDEN',
  QUIZ_ALREADY_ATTEMPTED: 'QUIZ_ALREADY_ATTEMPTED',
  QUIZ_ASSIGNMENT_NOT_FOUND: 'QUIZ_ASSIGNMENT_NOT_FOUND',
  QUIZ_CLOSED: 'QUIZ_CLOSED',
  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  ATTEMPT_ALREADY_SUBMITTED: 'ATTEMPT_ALREADY_SUBMITTED',
  ATTEMPT_NOT_IN_PROGRESS: 'ATTEMPT_NOT_IN_PROGRESS',
  ATTEMPT_FORBIDDEN: 'ATTEMPT_FORBIDDEN',
  QUIZ_ANSWER_NOT_FOUND: 'QUIZ_ANSWER_NOT_FOUND',

  // Labs
  LAB_NOT_FOUND: 'LAB_NOT_FOUND',
  LAB_FORBIDDEN: 'LAB_FORBIDDEN',
  LAB_NOT_PUBLISHABLE: 'LAB_NOT_PUBLISHABLE',
  LAB_NOT_REJECTABLE: 'LAB_NOT_REJECTABLE',
  LAB_NOT_REFINABLE: 'LAB_NOT_REFINABLE',
  LAB_NOT_RESTARTABLE: 'LAB_NOT_RESTARTABLE',
  LAB_NOT_PUBLISHED: 'LAB_NOT_PUBLISHED',

  // Submissions / grading
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_EXISTS: 'SUBMISSION_ALREADY_EXISTS',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_ID_REQUIRED: 'ASSIGNMENT_ID_REQUIRED',
  SUBMISSION_NO_TEXT: 'SUBMISSION_NO_TEXT',
  PDF_NO_TEXT: 'PDF_NO_TEXT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  SCORE_NOT_FOUND: 'SCORE_NOT_FOUND',

  // Rubrics / materials
  RUBRIC_NOT_FOUND: 'RUBRIC_NOT_FOUND',
  RUBRIC_CRITERIA_NOT_FOUND: 'RUBRIC_CRITERIA_NOT_FOUND',
  MATERIAL_NOT_FOUND: 'MATERIAL_NOT_FOUND',
  CHAPTER_NOT_FOUND: 'CHAPTER_NOT_FOUND',
  FILE_NO_TEXT: 'FILE_NO_TEXT',
  INVALID_UPLOAD_TARGET: 'INVALID_UPLOAD_TARGET',

  // Users (admin)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DELETE_FORBIDDEN: 'USER_DELETE_FORBIDDEN',

  // Students / teachers / grades
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  GUARDIAN_NOT_FOUND: 'GUARDIAN_NOT_FOUND',
  TEACHER_HAS_OFFERINGS: 'TEACHER_HAS_OFFERINGS',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  ALERT_NOT_FOUND: 'ALERT_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',

  // Broadcasts
  BROADCAST_NOT_FOUND: 'BROADCAST_NOT_FOUND',
  BROADCAST_AUDIENCE_EMPTY: 'BROADCAST_AUDIENCE_EMPTY',

  // Chat
  THREAD_NOT_FOUND: 'THREAD_NOT_FOUND',
  THREAD_NOT_PARTICIPANT: 'THREAD_NOT_PARTICIPANT',
  CHAT_FORBIDDEN: 'CHAT_FORBIDDEN',

  // Insights
  INSIGHTS_FORBIDDEN: 'INSIGHTS_FORBIDDEN',
  INSIGHTS_STUDENT_NOT_FOUND: 'INSIGHTS_STUDENT_NOT_FOUND',
  INSIGHTS_SECTION_NOT_FOUND: 'INSIGHTS_SECTION_NOT_FOUND',

  // Homework helper
  INTERACTION_NOT_FOUND: 'INTERACTION_NOT_FOUND',
  HOMEWORK_FORBIDDEN: 'HOMEWORK_FORBIDDEN',

  // Student documents & fees
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_UPLOAD_FAILED: 'DOCUMENT_UPLOAD_FAILED',
  DOCUMENT_ASSIGNMENT_NOT_FOUND: 'DOCUMENT_ASSIGNMENT_NOT_FOUND',
  BULK_UPLOAD_EMPTY: 'BULK_UPLOAD_EMPTY',
  CSV_PARSE_ERROR: 'CSV_PARSE_ERROR',
  CSV_IMPORT_EMPTY: 'CSV_IMPORT_EMPTY',
  FEE_NOT_FOUND: 'FEE_NOT_FOUND',
  FEE_CONFLICT: 'FEE_CONFLICT',

  // Teacher documents & salary
  TEACHER_DOCUMENT_NOT_FOUND: 'TEACHER_DOCUMENT_NOT_FOUND',
  TEACHER_DOCUMENT_UPLOAD_FAILED: 'TEACHER_DOCUMENT_UPLOAD_FAILED',
  SALARY_NOT_FOUND: 'SALARY_NOT_FOUND',
  SALARY_CONFLICT: 'SALARY_CONFLICT',

  // Teacher profile (SSN / photo)
  SSN_ENCRYPTION_NOT_CONFIGURED: 'SSN_ENCRYPTION_NOT_CONFIGURED',
  SSN_INVALID: 'SSN_INVALID',
  PHOTO_INVALID: 'PHOTO_INVALID',
  PHOTO_UPLOAD_FAILED: 'PHOTO_UPLOAD_FAILED',
  PHOTO_REQUIRED: 'PHOTO_REQUIRED',
  AVATAR_NOT_FOUND: 'AVATAR_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
